import { useQueryClient } from '@tanstack/react-query'
import { useCallback } from 'react'

const DERIVED = ['summary', 'timeseries', 'breakdown', 'monthly', 'forecast', 'anomalies', 'goals', 'scenario-baseline', 'scenario', 'org-dashboard', 'achievements']
const BACKGROUND = ['insights', 'recommendations', 'achievements']

/**
 * After activities change, refresh everything derived from them. Insights/recommendations are
 * regenerated by a backend background task after the response, so they are refetched again shortly.
 */
export function useInvalidateEmissions() {
  const qc = useQueryClient()
  return useCallback(() => {
    qc.invalidateQueries({ queryKey: ['activities'] })
    DERIVED.forEach((k) => qc.invalidateQueries({ queryKey: [k] }))
    BACKGROUND.forEach((k) => qc.invalidateQueries({ queryKey: [k] }))
    window.setTimeout(() => BACKGROUND.forEach((k) => qc.invalidateQueries({ queryKey: [k] })), 2500)
  }, [qc])
}
