"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 08:49:08.429142
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('join_code', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('join_code', name=op.f('uq_organizations_join_code'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('org_role', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("org_role is null or org_role in ('owner', 'member')", name=op.f('ck_users_org_role_valid')),
    sa.CheckConstraint("role in ('user', 'admin')", name=op.f('ck_users_role_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # organizations <-> users reference each other; add this FK once both tables exist.
    op.create_foreign_key(op.f('fk_organizations_created_by_id_users'), 'organizations', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_table('achievements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('user_id', 'code', name='uq_achievements_user_code')
    )
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('activities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('activity_type', sa.String(length=48), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category in ('transport', 'flights', 'energy', 'food', 'waste', 'consumption', 'digital', 'business', 'other')", name=op.f('ck_activities_category_valid')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_activities_quantity_non_negative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_activities_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_organization_id'), 'activities', ['organization_id'], unique=False)
    op.create_index('ix_activities_user_date', 'activities', ['user_id', 'occurred_on'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('emission_factors',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('co2e_per_unit', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category in ('transport', 'flights', 'energy', 'food', 'waste', 'consumption', 'digital', 'business', 'other')", name=op.f('ck_emission_factors_category_valid')),
    sa.CheckConstraint("quality in ('high', 'medium', 'low')", name=op.f('ck_emission_factors_quality_valid')),
    sa.CheckConstraint('co2e_per_unit >= 0', name=op.f('ck_emission_factors_co2e_non_negative')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_emission_factors_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_factors')),
    sa.UniqueConstraint('key', 'region', 'version', name='uq_emission_factors_key_region_version')
    )
    op.create_index('ix_emission_factors_lookup', 'emission_factors', ['key', 'region', 'is_active'], unique=False)
    op.create_table('goals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=True),
    sa.Column('baseline_monthly_kg', sa.Float(), nullable=False),
    sa.Column('target_reduction_pct', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active', 'achieved', 'missed', 'archived')", name=op.f('ck_goals_status_valid')),
    sa.CheckConstraint('baseline_monthly_kg >= 0', name=op.f('ck_goals_baseline_non_negative')),
    sa.CheckConstraint('target_reduction_pct > 0 and target_reduction_pct <= 100', name=op.f('ck_goals_reduction_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_index('ix_goals_user_status', 'goals', ['user_id', 'status'], unique=False)
    op.create_table('insights',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('insight_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("severity in ('positive', 'info', 'warning')", name=op.f('ck_insights_severity_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_insights_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    op.create_index('ix_insights_user_generated', 'insights', ['user_id', 'generated_at'], unique=False)
    op.create_table('predictions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('predicted_total_kg', sa.Float(), nullable=True),
    sa.Column('lower_total_kg', sa.Float(), nullable=True),
    sa.Column('upper_total_kg', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_predictions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index('ix_predictions_user_generated', 'predictions', ['user_id', 'generated_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rec_key', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('current_behavior', sa.String(length=300), nullable=False),
    sa.Column('suggested_action', sa.String(length=300), nullable=False),
    sa.Column('estimated_monthly_reduction_kg', sa.Float(), nullable=False),
    sa.Column('share_of_footprint_pct', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.String(length=8), nullable=False),
    sa.Column('calculation_basis', sa.Text(), nullable=False),
    sa.Column('data_basis', sa.String(length=24), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("difficulty in ('easy', 'medium', 'hard')", name=op.f('ck_recommendations_difficulty_valid')),
    sa.CheckConstraint("status in ('open', 'accepted', 'dismissed', 'completed')", name=op.f('ck_recommendations_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('user_id', 'rec_key', name='uq_recommendations_user_key')
    )
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('distance_unit', sa.String(length=4), nullable=False),
    sa.Column('default_range', sa.String(length=8), nullable=False),
    sa.Column('monthly_budget_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("default_range in ('7d', '30d', '90d', '180d', '365d')", name=op.f('ck_user_preferences_default_range_valid')),
    sa.CheckConstraint("distance_unit in ('km', 'mi')", name=op.f('ck_user_preferences_distance_unit_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_preferences'))
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('primary_transport', sa.String(length=32), nullable=True),
    sa.Column('vehicle_type', sa.String(length=32), nullable=True),
    sa.Column('weekly_car_km', sa.Float(), nullable=True),
    sa.Column('weekly_public_transport_km', sa.Float(), nullable=True),
    sa.Column('short_haul_flights_per_year', sa.Integer(), nullable=True),
    sa.Column('long_haul_flights_per_year', sa.Integer(), nullable=True),
    sa.Column('monthly_electricity_kwh', sa.Float(), nullable=True),
    sa.Column('renewable_share_pct', sa.Float(), nullable=True),
    sa.Column('heating_fuel', sa.String(length=32), nullable=True),
    sa.Column('monthly_heating_kwh', sa.Float(), nullable=True),
    sa.Column('diet_type', sa.String(length=32), nullable=True),
    sa.Column('shopping_level', sa.String(length=16), nullable=True),
    sa.Column('monthly_clothing_spend_usd', sa.Float(), nullable=True),
    sa.Column('monthly_electronics_spend_usd', sa.Float(), nullable=True),
    sa.Column('weekly_waste_kg', sa.Float(), nullable=True),
    sa.Column('recycling_level', sa.String(length=16), nullable=True),
    sa.Column('composts', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('household_size is null or household_size between 1 and 20', name=op.f('ck_user_profiles_household_size_range')),
    sa.CheckConstraint('renewable_share_pct is null or (renewable_share_pct >= 0 and renewable_share_pct <= 100)', name=op.f('ck_user_profiles_renewable_share_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_profiles'))
    )
    op.create_table('emission_records',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('activity_type', sa.String(length=48), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('emission_factor_id', sa.Uuid(), nullable=True),
    sa.Column('factor_key', sa.String(length=80), nullable=False),
    sa.Column('factor_value', sa.Float(), nullable=False),
    sa.Column('factor_unit', sa.String(length=24), nullable=False),
    sa.Column('factor_source', sa.String(length=300), nullable=False),
    sa.Column('normalized_quantity', sa.Float(), nullable=False),
    sa.Column('co2e_kg', sa.Float(), nullable=False),
    sa.Column('calculation_method', sa.Text(), nullable=False),
    sa.Column('data_quality', sa.String(length=8), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category in ('transport', 'flights', 'energy', 'food', 'waste', 'consumption', 'digital', 'business', 'other')", name=op.f('ck_emission_records_category_valid')),
    sa.CheckConstraint("data_quality in ('high', 'medium', 'low')", name=op.f('ck_emission_records_quality_valid')),
    sa.CheckConstraint('co2e_kg >= 0', name=op.f('ck_emission_records_co2e_non_negative')),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_emission_records_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], name=op.f('fk_emission_records_emission_factor_id_emission_factors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_emission_records_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emission_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_records')),
    sa.UniqueConstraint('activity_id', name=op.f('uq_emission_records_activity_id'))
    )
    op.create_index('ix_emission_records_org_date', 'emission_records', ['organization_id', 'occurred_on'], unique=False)
    op.create_index('ix_emission_records_user_cat_date', 'emission_records', ['user_id', 'category', 'occurred_on'], unique=False)
    op.create_index('ix_emission_records_user_date', 'emission_records', ['user_id', 'occurred_on'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('context_used', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role in ('user', 'assistant')", name=op.f('ck_messages_role_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_organizations_created_by_id_users'), 'organizations', type_='foreignkey')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_emission_records_user_date', table_name='emission_records')
    op.drop_index('ix_emission_records_user_cat_date', table_name='emission_records')
    op.drop_index('ix_emission_records_org_date', table_name='emission_records')
    op.drop_table('emission_records')
    op.drop_table('user_profiles')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_predictions_user_generated', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_insights_user_generated', table_name='insights')
    op.drop_table('insights')
    op.drop_index('ix_goals_user_status', table_name='goals')
    op.drop_table('goals')
    op.drop_index('ix_emission_factors_lookup', table_name='emission_factors')
    op.drop_table('emission_factors')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_activities_user_date', table_name='activities')
    op.drop_index(op.f('ix_activities_organization_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
